### PR TITLE
Make the client actually good

### PR DESCRIPTION
**Pull request by StijnSimons**
- [X] Improved QoL
- [X] Minor backend fixes
- [X] Bug fixes
- [X] Performance issues
- [X] License issues fixed

### CODE REVIEW

**Comment by StijnSimons** [comment]
Fixes #1

**Comment by EmeraldSnorlax** [comment]
Fixes #1, LGTM!

**Comment by dominikaaaa** [comment]
lgtm

**Comment by Ilidumb** [comment]
Yeap, this will make release like a week sooner. LGTM, ready for merge

**Comment by iBuyMountainDew** [comment]
future is no match

**Comment by EmeraldSnorlax** [comment]
Thank for you adding a code of conduct, should simplify contributing in the future!

**Comment by EmeraldSnorlax** [comment]
ZeroDay
Could we perhaps get a UI rewrite too?

**Comment by StijnSimons** [comment]
> ZeroDay
> Could we perhaps get a UI rewrite too? Right now a skidded client has copied another client which is now being skidded here.

this is true, i expect these changes to be finished by 2021

**Comment by EmeraldSnorlax** [comment]
Perhaps start a new branch for the UI rewrite?

**Comment by RealIndrit** [comment]
1.16 when?

**Comment by StijnSimons** [comment]
> 1.16 when?

fuck off

**Comment by EmeraldSnorlax** [comment]
> 1.16 when?
Let's not put the cart before the horse

**Comment by StijnSimons** [comment]
> > 1.16 when?
> > Let's not put the cart before the horse

first release when

**Comment by EmeraldSnorlax** [comment]
When this guys russian internet finishes cloning aristois to create the holy trinity of skidded clients

**Comment by RealIndrit** [comment]
Hardware id locked when?

**Comment by iBuyMountainDew** [comment]
Please answer us, we put in the effort to contribute and suggest, and we get nothing back! :(

**Comment by ollieobama** [comment]
this is very needed!!! i will code the godlieyist modules!! <3

**Comment by zPeanut** [comment]
I approve.

**Comment by Bluskript** [comment]
Merge this!

**Comment by StijnSimons** [comment]
Thanks for all the approves! Hope this gets merged soon!

**Comment by Ilidumb** [comment]
based

**Comment by repository** [comment]
lgtm, already running locally

**Comment by RealIndrit** [comment]
Aristois btc miner removed? damn the performance boost will be insane!!!

**Comment by dominikaaaa** [comment]
wtf noo 😭😭

**Pull request closed without merging**
