### PR TITLE
♿

### PR DESCRIPTION
**Pull request by repository**
♿

### CODE REVIEW

**Comment by StijnSimons** [comment]
This one build up to pr #3, the functionality goes through the roof, performance better than ever! I recommend adding fabritone for extra utility.

**Comment by repository** [comment]
Ignore CI, actually builds but fails here for some reason

**Comment by zPeanut** [comment]
As I've compiled the code for around 5 times, I've seen that the code presented here by the User repository dropped my GPU Usage, which before was at 100% constantly, now drops to below 5%. Merge this fast!

**Comment by StijnSimons** [comment]
yes CI is just a third world issue anyways

**Comment by EmeraldSnorlax** [comment]
CI can't comprehend the god tier brain behind this code

**Comment by Ilidumb** [comment]
user error

**Comment by cattyngmd** [comment]
stop skidding

**Comment by cattyngmd** [comment]
offeex stop skidding

**Comment by Bluskript** [comment]
Even github supports this project. I am looking forward for more future commits from repository!

**Comment by xTMMDx** [comment]
Это уже есть в клиенте

**Comment by cattyngmd** [comment]
uwu

**Comment by iBuyMountainDew** [comment]
mhm yes mhm

**Comment by iBuyMountainDew** [comment]
ayyyy through this i can talk on your shitty discord!!

**Comment by iBuyMountainDew** [comment]
we'll be back nerds, prepare to get your arses deleted again

**Comment by dominikaaaa** [comment]
why was this closed :((

**Pull request closed without merging**
